server.servlet.context-path: /templatemultiservice
management.endpoints.web:
  base-path: /manage
  exposure.include: "*"

appinfo:
  title: Template Multi Module Spring Boot Service
  description: Skeleton service using Spring Boot with multiple modules

server:
  port: 8082